development:
  EMAIL_USERNAME:  ""
  EMAIL_PASSWORD:  ""
  EMAIL_PORT:      ""
  EMAIL_SMTPSRVR:  ""
  EMAIL_DOMAIN:    ""
    # Stripe Keys
  PUBLISHABLE_KEY:   ""
  SECRET_KEY:        ""

production:
  EMAIL_USERNAME:  ""
  EMAIL_PASSWORD:  ""
  EMAIL_PORT:      ""
  EMAIL_SMTPSRVR:  ""
  EMAIL_DOMAIN:    ""
  # stripe keys
  PUBLISHABLE_KEY:   ""
  SECRET_KEY:        ""